import ContactLinks from "@/components/ContactLinks";
import Hero from "@/components/Hero";
import World from "@/components/World";
import Head from "next/head";
import React from "react";

const work = () => {
  return (
    <div>
      <Head>
        <title>Avery Work</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero
        heading="Contact"
        message="You can contact me via these social links down below."
        btnName={"See Below"}
        linkTo={"contact-links"}
      />
      <ContactLinks />
    </div>
  );
};

export default work;
