import Hero from "@/components/Hero";
import World from "@/components/World";
import Head from "next/head";
import React from "react";

const work = () => {
  return (
    <div>
      <Head>
        <title>Avery Contact</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero
        heading="My Works"
        message="These are some of my recent works travelling the world."
        btnName={"See Below"}
        linkTo={"world"}
      />
      <World />
    </div>
  );
};

export default work;
